github/azuread nonce with ui type
rancher/ui pull request #4494
Opened 2021-03-09 16:05 UTC by mantis-toboggan-md

https://github.com/rancher/rancher/issues/31562
As of this pr https://github.com/rancher/rancher/pull/31563 `/verify-auth` and `/verify-auth-azure` routes should redirect based off the `state` query param. related vue pr: https://github.com/rancher/dashboard/pull/2477

* update auth flows in ember to include a base64 encoded state param to redirect to the correct UI 
* update auth route to` /verify` instead of` /verify-auth` and `/verify-auth-azure`
* include state query param/nonce check for azuread auth

2021-03-09 19:03 UTC, westlywright requested changes

2021-03-09 19:03 UTC, westlywright commented on lib/shared/addon/pipeline-github/service.js
> +    const state = JSON.stringify({
I know you're simply adding logic to an existing method but I think this also falls under the same comment above as to why we're not using the oauth service here?

2021-03-10 14:58 UTC, mantis-toboggan-md commented on app/verify-auth-azure/route.js
> +  model() {
Done

2021-03-10 14:58 UTC, mantis-toboggan-md commented on lib/shared/addon/azure-ad/service.js
> +  generateState() {
No you're right there's no need to duplicate this logic; I updated the azure-ad and pipeline-github services to use state functions from the oauth service.

2021-03-10 18:59 UTC, westlywright approved these changes

2021-03-10 20:16 UTC, merged