Add rke1 cloud provider for harvester
rancher/ui pull request #4778
Opened 2021-11-04 09:19 UTC by n313893254

Proposed changes
======

Types of changes
======

- New feature (non-breaking change which adds functionality)

Linked Issues
======

https://github.com/rancher/rancher/issues/35000

 

Further comments
======

2021-11-17 15:12 UTC, n313893254 commented
[Backend PR](https://github.com/rancher/rke/pull/2733) has merged.

@richard-cox Could you help review this PR? thanks. cc @nwmac

2021-11-22 18:11 UTC, richard-cox requested changes

2021-11-24 07:01 UTC, n313893254 commented on lib/shared/addon/components/cru-cloud-provider/component.js
> +    const cloudCredentialId = get(this, 'model.nodeTemplates.firstObject.cloudCredentialId')
Done

2021-11-24 07:03 UTC, n313893254 commented
Hi, @richard-cox. Thanks for your review, I fixed the comments, PTAL, thanks.

2021-11-24 12:05 UTC, richard-cox requested changes
TBH I'm not sure of the flow here, however when selecting `Harvester (Out-of-tree)` in an install without any harvester instances it flashes up a notice on the right which is quickly removed and doesn't change the radio button selection.

The underlying error is 
```
Assertion Failed: Cannot call get with 'harvestercredentialConfig.clusterId' on an undefined object.
```
So i'm guessing there's no
```
const cloudCredential = Ember.get(this, 'globalStore').getById('cloudCredential', cloudCredentialId);
```

Should the option be visible / enabled if it's not possible to use? The creds are something supplied with the node template above correct, if so maybe the option can be disabled until set?

2021-11-24 16:16 UTC, n313893254 commented
Thanks a lot, the comment truely helps me. Now the option can not be selected before select a node template first. And added a tooptip to notify user should select a node template.

![image](https://user-images.githubusercontent.com/18737885/143275172-6f805349-feed-417f-8ff8-4cda75bbe5cd.png)

2021-11-24 17:57 UTC, richard-cox approved these changes

2021-11-24 17:58 UTC, merged