Remove use of JsZip
rancher/ui pull request #5167
Opened 2024-09-05 17:32 UTC by nwmac

This PR removes the JsZip library.

This was only being used in 2 parts of the codebase - cis scans and pipelines - both of these are no longer shown in the UI.

For simplicity, the code has been removed and errors are logged - these code paths should not be reachable in the UI - we will prune this code in the future as part of a larger tidy-up effort.

2024-09-05 23:06 UTC, mantis-toboggan-md requested changes

2024-09-09 10:48 UTC, nwmac commented
Removed downloadYaml, as the backend API does not work and this is legacy UI

2024-09-09 15:10 UTC, mantis-toboggan-md approved these changes

2024-09-09 15:23 UTC, nwmac commented
@mantis-toboggan-md Updated following merge of dependabot PR

2024-09-09 15:26 UTC, mantis-toboggan-md approved these changes

2024-09-09 15:38 UTC, merged